language: cpp

compiler:
  - clang
  - gcc

os:
  - linux
  - osx
  - windows

dist: trusty

notifications:
  email: false

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then PATH="$PATH:/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin"; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then powershell ./build.bat; else ./build.sh; fi
