language: cpp

compiler:
  - clang
  - gcc

os:
  - linux
  - osx
  - windows

dist: Bionic
osx_image: xcode11.3

notifications:
  email: false

before_deploy:
  - export TRAVIS_TAG="v0.5.1"

jobs:
  include:
    - os: linux
      stage: Publish
      script:
        - npm run dist
      deploy:
        provider: releases
        api_key: $GH_TOKEN
        file:
          - "dist/OpenRPG-0.5.1-Linux.deb"
          - "dist/OpenRPG-0.5.1-Linux.deb.sha512"
          - "dist/OpenRPG-0.5.1-Linux.sh"
          - "dist/OpenRPG-0.5.1-Linux.sh.sha512"
          - "dist/OpenRPG-0.5.1-Linux.tar.gz"
          - "dist/OpenRPG-0.5.1-Linux.tar.gz.sha512"
          - "dist/OpenRPG-0.5.1-Linux.tar.xz"
          - "dist/OpenRPG-0.5.1-Linux.tar.xz.sha512"
          - "dist/OpenRPG-0.5.1-Linux.tar.Z"
          - "dist/OpenRPG-0.5.1-Linux.tar.Z.sha512"
        overwrite: true
        skip_cleanup: true
        draft: true
        prerelease: true
    - os: osx
      stage: Publish
      script: 
        - npm run dist
      deploy:
        provider: releases
        api_key: $GH_TOKEN
        file:
          - "dist/OpenRPG-0.5.1-Darwin.sh"
          - "dist/OpenRPG-0.5.1-Darwin.sh.sha512"
          - "dist/OpenRPG-0.5.1-Darwin.tar.gz"
          - "dist/OpenRPG-0.5.1-Darwin.tar.gz.sha512"
        overwrite: true
        skip_cleanup: true
        draft: true
        prerelease: true
    - os: windows
      stage: Publish
      script: 
        - npm run dist
      deploy:
        provider: releases
        api_key: $GH_TOKEN
        file:
          - "dist/OpenRPG-0.5.1-win64.exe"
          - "dist/OpenRPG-0.5.1-win64.exe.sha512"
          - "dist/OpenRPG-0.5.1-win64.tar.gz"
          - "dist/OpenRPG-0.5.1-win64.tar.gz.sha512"
          - "dist/OpenRPG-0.5.1-win64.zip"
          - "dist/OpenRPG-0.5.1-win64.zip.sha512"
        overwrite: true
        skip_cleanup: true
        draft: true
        prerelease: true

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash; nvm install node; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install nodejs nsis; PATH="$PATH:/c/Program Files/nodejs:/c/Program Files (x86)/NSIS"; fi

install:
  - npm install && npm run clean && npm run compile

script:
  - npm test