sudo: false
language: cpp

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

dist: trusty

notifications:
  email: false

before_install:
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=~/local ..
  - make check

script:
  - make install
