language: cpp

compiler:
  - clang
  - gcc
  - llvm

os:
  - linux
  - osx
  - windows

notifications:
  email: false

jobs:
  include:
    - stage: GitHub Release
      script: 
        - npm run dist
      deploy:
        provider: releases
        api_key: $GH_TOKEN
        name: "v0.5.0"
        tag_name: "v0.5.0"
        - os: linux
            file:
            - "build/OpenRPG-0.5.0-Linux.deb"
            - "build/OpenRPG-0.5.0-Linux.sh"
            - "build/OpenRPG-0.5.0-Linux.tar.gz"
            - "build/OpenRPG-0.5.0-Linux.tar.xz"
            - "build/OpenRPG-0.5.0-Linux.tar.Z"
            - "build/OpenRPG-0.5.0-Linux.sha512"
        - os: osx
          file:
            - "build/OpenRPG-0.5.0-Darwin.sh"
            - "build/OpenRPG-0.5.0-Darwin.sh.sha512"
            - "build/OpenRPG-0.5.0-Darwin.tar.gz"
            - "build/OpenRPG-0.5.0-Darwin.tar.gz.sha512"
        - os: windows
          file:
            - "build/OpenRPG-0.5.0-win64.exe"
            - "build/OpenRPG-0.5.0-win64.exe.sha512"
        overwrite: true
        skip_cleanup: true
        draft: true
        prerelease: true

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash; nvm install node; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install nodejs nsis; PATH="$PATH:/c/Program Files/nodejs:/c/Program Files (x86)/NSIS"; fi

install:
  - npm install && npm run clean && npm run compile

script:
  - npm test