language:
  - cpp
  - node_js

compiler:
  - clang
  - gcc
  - llvm

os:
  - linux
  - osx
  - windows

notifications:
  email: false

jobs:
  include:
    - os: windows
      stage: GitHub Release
      script: 
        - echo "Deploying to GitHub releases ..."
        - cd build && cmake --build . --target package && cd ..
      deploy:
        provider: releases
        api_key: $GH_TOKEN
        file:
          - "build/OpenRPG-0.5.0-win64.exe"
          - "build/OpenRPG-0.5.0-win64.exe.sha512"
        overwrite: true
        skip_cleanup: true
        draft: true

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then PATH="$PATH:/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin"; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install nodejs; PATH="$PATH:/c/Program Files/nodejs"; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then powershell ./build.bat release; else ./build.sh release; fi

script:
  - cd build && npm -v && cd ..