# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  auto_ids: true

# Permalinks
permalink:        pretty

# Server
destination:      build
url:              http://openrpg.io
encoding:         UTF-8

gems:
  - jekyll-redirect-from
  - jekyll-sitemap

# Social
title: OpenRPG
description: You're tabletop RPG workbench!
authors: Nick Gaulke

# Custom vars
current_version:  0.4.0-dev
repo:             https://github.com/incomingstick/OpenRPG
chat:             https://discord.gg/xEwaYE5
blog:             http://blog.openrpg.io

download:
  source:         https://github.com/incomingstick/OpenRPG/archive/v0.4.0-dev.zip
  dist:           https://github.com/incomingstick/OpenRPG/archive/v0.4.0-dev.zip
