# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  auto_ids: true

# Permalinks
permalink:        pretty

# Server
destination:      build
url:              http://openrpg.io
encoding:         UTF-8

gems:
  - jekyll-redirect-from
  - jekyll-sitemap

# Social
title: OpenRPG
description: A handy dandy helper program for playing D&D!
authors: Nick Gaulke

# Custom vars
current_version:  0.3.0-dev
repo:             https://github.com/incomingstick/OpenRPG
discord:        https://discord.gg/xEwaYE5

download:
  source:         https://github.com/incomingstick/OpenRPG/archive/v0.3.0-dev.zip
  dist:           https://github.com/incomingstick/OpenRPG/archive/v0.3.0-dev.zip
