# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  auto_ids: true

# Permalinks
permalink:        pretty

# Server
destination:      build
url:              http://openrpg.io
encoding:         UTF-8

include:
  - /.well-known/brave-rewards-verification.txt

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag

# Social
title: OpenRPG
description: Your up to date tabletop RPG workbench!
authors: Nicholas Gaulke

# SEO
logo:   /assets/images/logos/logo.jpg
image:  /assets/images/logos/logo.jpg
webmaster_verifications:
  google: EugX-uWEf8uZsqe6jeR8UN8BM1Du88Zq27dh-ORFB50

author:
  twitter: incomingstick

# Custom vars
current_version:  0.4.4-dev
repo:               https://github.com/incomingstick/OpenRPG
chat:               https://discord.gg/xEwaYE5
blog:               http://blog.openrpg.io

d20_blue:  /assets/images/logos/d20_blue.jpg

download:
  source:       https://github.com/incomingstick/OpenRPG/archive/v0.4.4-dev.zip
  dist:         https://github.com/incomingstick/OpenRPG/archive/v0.4.4-dev.zip
