[package]
name = "openrpg-api"
version = "0.1.0"
authors = ["Michael AKA hurnhu  <hurnhu@protonmail.com>"]

[dependencies]
rocket = "0.4.5"
rocket_codegen = "0.4.5"
serde = "1.0.2"
serde_json = "1.0.1"
serde_derive = "1.0.2"
